# 4.6 GPU计算

In [44]:
!nvidia-smi # 对Linux/macOS用户有效

Mon Nov 22 15:57:03 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.00    Driver Version: 470.82.00    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:3B:00.0 Off |                  N/A |
| 37%   66C    P2   124W / 350W |  24265MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:B1:00.0 Off |                  N/A |
| 56%   

In [45]:
import torch
from torch import nn

print(torch.__version__)

1.10.0


## 4.6.1 计算设备

In [46]:
torch.cuda.is_available() # cuda是否可用

True

In [47]:
torch.cuda.device_count() # gpu数量

3

In [48]:
torch.cuda.current_device() # 当前设备索引, 从0开始

0

In [49]:
torch.cuda.get_device_name(0) # 返回gpu名字

'NVIDIA GeForce RTX 3090'

## 4.6.2 `Tensor`的GPU计算

In [50]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [51]:
x = x.cuda(1)
x

tensor([1, 2, 3], device='cuda:1')

In [52]:
x.device

device(type='cuda', index=1)

In [53]:
device = torch.device('cuda:1' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
# or
x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:1')

In [54]:
y = x**2
y

tensor([1, 4, 9], device='cuda:1')

In [55]:
# z = y + x.cpu()

## 4.6.3 模型的GPU计算

In [56]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [57]:
net.cuda()
list(net.parameters())[0].device

RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

In [ ]:
x = torch.rand(2,3).cuda()
net(x)

tensor([[-0.5574],
        [-0.3792]], device='cuda:0', grad_fn=<ThAddmmBackward>)